# -*- coding: utf-8 -*-
"""BlackWoodStair_autoContrast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0EexKth0VoB2p0ETe47BQ0umyDdaC5Z
"""

!curl -L "https://app.roboflow.com/ds/apDGmzuuun?key=bj5M48w9NT" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5/
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cat /content/dataset/data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /
from glob import glob

test_list = glob('/content/dataset/test/images/*.jpg')
valid_list = glob('/content/dataset/valid/images/*.jpg')
train_list = glob('/content/dataset/train/images/*.jpg')


print(len(test_list))
print(len(valid_list))
print(len(train_list))

with open('/content/dataset/train.txt', 'w') as f:
  f.write('\n'.join(train_list) + '\n')

with open('/content/dataset/val.txt', 'w') as f:
  f.write('\n'.join(valid_list) + '\n')

import yaml

with open('/content/dataset/data.yaml', 'r') as f:
  data = yaml.safe_load(f)

print(data)

data['train'] = '/content/dataset/train.txt'
data['val'] = '/content/dataset/val.txt'

with open('/content/dataset/data.yaml', 'w') as f:
  yaml.dump(data, f)

print(data)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5/
!python train.py --img 416 --batch 16 --epochs 50 --data /content/dataset/data.yaml --cfg ./models/yolov5l.yaml --weights yolov5l.pt --name blackWoodStair

